spring.application.name=ms-bff

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=false

server.port=${PORT}

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

ms-catalogo.url=${MS_CATALOGO_URL}
ms-pedidos.url=${MS_PEDIDOS_URL}

spring.datasource.hikari.connection-init-sql=SET search_path=public
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=2