spring.application.name=ms-bff

# Conexion a Supabase (Postgres) - Shared Pooler. El BFF solo necesita la tabla "usuarios" para auth.
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.dtudhbhgymaimhddyotx
spring.datasource.password=FQFqnoR17PONJji7
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# El BFF corre en el puerto 8080, igual que el monolito original (asi el frontend no necesita cambios)
server.port=8080

# JWT
jwt.secret=GGStore2026SecretKeyParaJWTMuyLargaYSeguraParaProduccion1234567890AbCdEfGhIjKlMnOp
jwt.expiration-ms=86400000

# URLs de los microservicios destino
ms-catalogo.url=http://localhost:8081
ms-pedidos.url=http://localhost:8082

# Hikari
spring.datasource.hikari.connection-init-sql=SET search_path=public
spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=false
